name: "gdalinfo"
description: "Snakemake wrapper for the gdalinfo tool"
authors: "zjh"

container: 
  image: "docker://docker.1ms.run/osgeo/gdal:ubuntu-small-3.6.3"

inputs:
  input_file:
    type: file
    description: "Raster input file"
outputs:
  output_file:
    type: file
    description: "gdalinfo metadata output text file."

log:
  description: "gdalinfo output written to log file"

params:
  gdalinfo_args:
    type: list
    default: ["-stats"]
    description: >
      "Arguments passed to gdalinfo"
      Usage: gdalinfo [--help-general] [-json] [-mm] [-stats | -approx_stats] [-hist] [-nogcp] [-nomd]
                [-norat] [-noct] [-nofl] [-checksum] [-proj4]
                [-listmdd] [-mdd domain|`all`] [-wkt_format WKT1|WKT2|...]*
                [-sd subdataset] [-oo NAME=VALUE]* [-if format]* datasetname

